# 基础镜像：锁定 2.1.x（与微服务 nacos-client 由 spring-cloud-alibaba 2021.0.5.0 管理为 2.1.x 对齐，见 pom.xml 的 alibaba.nacos.version）
FROM nacos/nacos-server:2.1.1
# author
MAINTAINER hcp

# 复制conf文件到路径
COPY ./conf/application.properties /home/nacos/conf/application.properties
